### ISSUE TITLE
rxd_err = 0x8

### ISSUE THREAD

**Issue by markbza** [acooks/tn40xx-driver#10]
Hi Friends! Thank you so much on your awesome work on this driver!!

We are running a 10gbit solution with your drivers on multiple machines. Our machines seem to lock up after a few days like clockwork. It starts giving rxd_err = 0x8 about a page full then the machine hard locks.

error is: rxd_err = 0x8
adapter model number is: Edimax EN-9320SFP+
kernel version:  4.15.18-30
driver version = latest (7months ago github)

Please advise what we can try?

**Comment by Infinality** [comment]
I don't actually know much about the modifications that acooks did to the drivers, but it might be described in a README somewhere.  If you are using the github version, you might try the stock upstream version, or vice versa.

**Comment by acooks** [comment]
overtaken by events
