### ISSUE TITLE
Version 0.3.6.17.2 released

### ISSUE THREAD

**Issue by N-Storm** [acooks/tn40xx-driver#13]
I've just downloaded it from Tehuti website.

**Comment by CHBMB** [comment]
@acooks I'm happy to submit a PR for the `0.3.6.17.2` vendor drop branch if you can create a branch for me to submit to.

**Comment by acooks** [comment]
vendor drop and cleanup branches created for 0.3.6.17.2. Release to follow once #14, #15 and #18 is resolved.
