### ISSUE TITLE
Linux 4.15

### ISSUE THREAD

**Issue by hronus** [acooks/tn40xx-driver#2]
Hello!

Does anyone try to build this driver for Linux 4.15? I tried it:

`make: Entering directory '/usr/src/linux-headers-4.15.17-1-pve'
make[1]: *** No rule to make target '/root/tn40xx-driver/tn40.o', needed by '/root/tn40xx-driver/tn40xx.o'.  Stop.
Makefile:1552: recipe for target '_module_/root/tn40xx-driver' failed
make: *** [_module_/root/tn40xx-driver] Error 2
make: Leaving directory '/usr/src/linux-headers-4.15.17-1-pve'`

P.S. Linux 4.13 built without errors

**Comment by acooks** [comment]
Hi

This error is related to the build environment, not the kernel version.

Could you post the exact commands and output, please?

Aside from this build issue, please consider working as a normal, non-root user when you clone and build the driver. Only the installation step requires root privileges.

**Comment by hronus** [comment]
pvei7 tn40xx-driver # git pull     
Already up-to-date.
pvei7 tn40xx-driver # git branch
* cleanup/v0.3.6.15

pvei7 tn40xx-driver # make -C /lib/modules/4.13.13-5-pve/build M=/root/tn40xx-driver clean
make: Entering directory '/usr/src/linux-headers-4.13.13-5-pve'
  CLEAN   /root/tn40xx-driver/.tmp_versions
  CLEAN   /root/tn40xx-driver/Module.symvers
make: Leaving directory '/usr/src/linux-headers-4.13.13-5-pve'
pvei7 tn40xx-driver # make -C /lib/modules/4.13.13-5-pve/build M=/root/tn40xx-driver 
make: Entering directory '/usr/src/linux-headers-4.13.13-5-pve'
  AR      /root/tn40xx-driver/built-in.o
  CC [M]  /root/tn40xx-driver/tn40.o
  CC [M]  /root/tn40xx-driver/CX4.o
  CC [M]  /root/tn40xx-driver/CX4_Linux.o
  CC [M]  /root/tn40xx-driver/QT2025_phy.o
  CC [M]  /root/tn40xx-driver/QT2025_phy_Linux.o
  CC [M]  /root/tn40xx-driver/TLK10232_phy.o
  CC [M]  /root/tn40xx-driver/TLK10232_phy_Linux.o
  CC [M]  /root/tn40xx-driver/AQR105_phy.o                                                                                
  CC [M]  /root/tn40xx-driver/AQR105_phy_Linux.o                                                                          
  LD [M]  /root/tn40xx-driver/tn40xx.o                                                                                    
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /root/tn40xx-driver/tn40xx.mod.o
  LD [M]  /root/tn40xx-driver/tn40xx.ko
make: Leaving directory '/usr/src/linux-headers-4.13.13-5-pve'

pvei7 tn40xx-driver # make -C /lib/modules/4.15.15-1-pve/build M=/root/tn40xx-driver clean  
make: Entering directory '/usr/src/linux-headers-4.15.15-1-pve'
  CLEAN   /root/tn40xx-driver/.tmp_versions
  CLEAN   /root/tn40xx-driver/Module.symvers
make: Leaving directory '/usr/src/linux-headers-4.15.15-1-pve'

pvei7 tn40xx-driver # make -C /lib/modules/4.15.15-1-pve/build M=/root/tn40xx-driver 
make: Entering directory '/usr/src/linux-headers-4.15.15-1-pve'
make[1]: *** No rule to make target '/root/tn40xx-driver/tn40.o', needed by '/root/tn40xx-driver/tn40xx.o'.  Stop.
Makefile:1552: recipe for target '_module_/root/tn40xx-driver' failed
make: *** [_module_/root/tn40xx-driver] Error 2
make: Leaving directory '/usr/src/linux-headers-4.15.15-1-pve'

Kernel headers installed: 

pvei7 tn40xx-driver # ls -l /usr/src/linux-headers-4.15.15-1-pve/
total 1684
-rw-r--r--   1 root root    2245 Apr  9 17:24 Kbuild
-rw-r--r--   1 root root     287 Apr  9 17:24 Kconfig
-rw-r--r--   1 root root   61472 Apr  9 17:24 Makefile
-rw-r--r--   1 root root 1535416 Apr  9 17:24 Module.symvers
drwxr-xr-x  33 root root    4096 May 14 09:27 arch
drwxr-xr-x   3 root root    4096 May 14 09:27 block
drwxr-xr-x   2 root root    4096 May 14 09:27 certs
drwxr-xr-x   4 root root    4096 May 14 09:27 crypto
drwxr-xr-x 131 root root    4096 May 14 09:27 drivers
drwxr-xr-x   2 root root    4096 May 14 09:27 firmware
drwxr-xr-x  75 root root    4096 May 14 09:27 fs
drwxr-xr-x  29 root root    4096 May 14 09:27 include
drwxr-xr-x   2 root root    4096 May 14 09:27 init
drwxr-xr-x   2 root root    4096 May 14 09:27 ipc
drwxr-xr-x  16 root root    4096 May 14 09:27 kernel
drwxr-xr-x  13 root root    4096 May 14 09:27 lib
drwxr-xr-x   3 root root    4096 May 14 09:27 mm
drwxr-xr-x  69 root root    4096 May 14 09:27 net
drwxr-xr-x  28 root root    4096 May 14 09:27 samples
drwxr-xr-x  14 root root   12288 May 14 09:27 scripts
drwxr-xr-x  10 root root    4096 May 14 09:27 security
drwxr-xr-x  25 root root    4096 May 14 09:27 sound
drwxr-xr-x  10 root root    4096 May 14 09:27 spl
drwxr-xr-x  29 root root    4096 May 14 09:27 tools
drwxr-xr-x   6 root root    4096 May 14 09:27 ubuntu
drwxr-xr-x   2 root root    4096 May 14 09:27 usr
drwxr-xr-x   4 root root    4096 May 14 09:27 virt
drwxr-xr-x   5 root root    4096 May 14 09:27 zfs

Try another kernel.

pvei7 tn40xx-driver # make -C /lib/modules/4.15.17-1-pve/build M=/root/tn40xx-driver 
make: Entering directory '/usr/src/linux-headers-4.15.17-1-pve'
make[1]: *** No rule to make target '/root/tn40xx-driver/tn40.o', needed by '/root/tn40xx-driver/tn40xx.o'.  Stop.
Makefile:1552: recipe for target '_module_/root/tn40xx-driver' failed
make: *** [_module_/root/tn40xx-driver] Error 2
make: Leaving directory '/usr/src/linux-headers-4.15.17-1-pve'
pvei7 tn40xx-driver # ls -l /usr/src/linux-headers-4.15.17-1-pve/
total 1688
-rw-r--r--   1 root root    2245 May  3 13:43 Kbuild
-rw-r--r--   1 root root     287 May  3 13:43 Kconfig
-rw-r--r--   1 root root   61472 May  3 13:43 Makefile
-rw-r--r--   1 root root 1536057 May  3 13:43 Module.symvers
drwxr-xr-x  33 root root    4096 May 10 00:06 arch
drwxr-xr-x   3 root root    4096 May 10 00:06 block
drwxr-xr-x   2 root root    4096 May 10 00:06 certs
drwxr-xr-x   4 root root    4096 May 10 00:06 crypto
drwxr-xr-x 131 root root    4096 May 10 00:06 drivers
drwxr-xr-x   2 root root    4096 May 10 00:06 firmware
drwxr-xr-x  75 root root    4096 May 10 00:06 fs
drwxr-xr-x  29 root root    4096 May 10 00:06 include
drwxr-xr-x   2 root root    4096 May 10 00:06 init
drwxr-xr-x   2 root root    4096 May 10 00:06 ipc
drwxr-xr-x  16 root root    4096 May 10 00:06 kernel
drwxr-xr-x  13 root root    4096 May 10 00:06 lib
drwxr-xr-x   3 root root    4096 May 10 00:06 mm
drwxr-xr-x  69 root root    4096 May 10 00:06 net
drwxr-xr-x  28 root root    4096 May 10 00:06 samples
drwxr-xr-x  14 root root   12288 May 10 00:06 scripts
drwxr-xr-x  10 root root    4096 May 10 00:06 security
drwxr-xr-x  25 root root    4096 May 10 00:06 sound
drwxr-xr-x  10 root root    4096 May 10 00:06 spl
drwxr-xr-x  29 root root    4096 May 10 00:06 tools
drwxr-xr-x   6 root root    4096 May 10 00:06 ubuntu
drwxr-xr-x   2 root root    4096 May 10 00:06 usr
drwxr-xr-x   4 root root    4096 May 10 00:06 virt
drwxr-xr-x   5 root root    4096 May 10 00:06 zfs

**Comment by acooks** [comment]
I don't know what the difference is between the 4.13 and 4.15 header packages on Proxmox. Let's try to find out.

Here's what I get on Fedora when I repeat the build steps with a 4.15 kernel:

[acooks@t460s tn40xx-driver]$ make -C /lib/modules/4.15.17-300.fc27.x86_64/build M=~/tn40xx-driver clean
make: Entering directory '/usr/src/kernels/4.15.17-300.fc27.x86_64'
  CLEAN   /home/acooks/tn40xx-driver/.tmp_versions
  CLEAN   /home/acooks/tn40xx-driver/Module.symvers
make: Leaving directory '/usr/src/kernels/4.15.17-300.fc27.x86_64'

[acooks@t460s tn40xx-driver]$ make -C /lib/modules/4.15.17-300.fc27.x86_64/build M=~/tn40xx-driver
make: Entering directory '/usr/src/kernels/4.15.17-300.fc27.x86_64'
  CC [M]  /home/acooks/tn40xx-driver/tn40.o
  CC [M]  /home/acooks/tn40xx-driver/CX4.o
  CC [M]  /home/acooks/tn40xx-driver/CX4_Linux.o
  CC [M]  /home/acooks/tn40xx-driver/MV88X3120_phy.o
  CC [M]  /home/acooks/tn40xx-driver/MV88X3120_phy_Linux.o
  CC [M]  /home/acooks/tn40xx-driver/MV88X3310_phy.o
  CC [M]  /home/acooks/tn40xx-driver/MV88X3310_phy_Linux.o
  CC [M]  /home/acooks/tn40xx-driver/QT2025_phy.o
  CC [M]  /home/acooks/tn40xx-driver/QT2025_phy_Linux.o
  CC [M]  /home/acooks/tn40xx-driver/TLK10232_phy.o
  CC [M]  /home/acooks/tn40xx-driver/TLK10232_phy_Linux.o
  CC [M]  /home/acooks/tn40xx-driver/AQR105_phy.o
  CC [M]  /home/acooks/tn40xx-driver/AQR105_phy_Linux.o
  LD [M]  /home/acooks/tn40xx-driver/tn40xx.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /home/acooks/tn40xx-driver/tn40xx.mod.o
  LD [M]  /home/acooks/tn40xx-driver/tn40xx.ko
make: Leaving directory '/usr/src/kernels/4.15.17-300.fc27.x86_64'

[acooks@t460s tn40xx-driver]$ ls -l /lib/modules/4.15.17-300.fc27.x86_64
total 15904
lrwxrwxrwx.  1 root root      40 Apr 13 04:37 build -> /usr/src/kernels/4.15.17-300.fc27.x86_64
-rw-r--r--.  1 root root  194527 Apr 13 04:36 config
drwxr-xr-x.  5 root root    4096 Apr 20 19:55 extra
drwxr-xr-x. 14 root root    4096 Apr 20 19:55 kernel
-rw-r--r--.  1 root root 1036746 Apr 20 20:03 modules.alias
-rw-r--r--.  1 root root 1012817 Apr 20 20:03 modules.alias.bin
-rw-r--r--.  1 root root    1749 Apr 13 04:37 modules.block
-rw-r--r--.  1 root root    7615 Apr 13 04:37 modules.builtin
-rw-r--r--.  1 root root   10056 Apr 20 20:03 modules.builtin.bin
-rw-r--r--.  1 root root  367212 Apr 20 20:03 modules.dep
-rw-r--r--.  1 root root  515986 Apr 20 20:03 modules.dep.bin
-rw-r--r--.  1 root root     381 Apr 20 20:03 modules.devname
-rw-r--r--.  1 root root     166 Apr 13 04:37 modules.drm
-rw-r--r--.  1 root root      95 Apr 13 04:37 modules.modesetting
-rw-r--r--.  1 root root    2622 Apr 13 04:37 modules.networking
-rw-r--r--.  1 root root  130982 Apr 13 04:37 modules.order
-rw-r--r--.  1 root root     515 Apr 20 20:03 modules.softdep
-rw-r--r--.  1 root root  428339 Apr 20 20:03 modules.symbols
-rw-r--r--.  1 root root  526362 Apr 20 20:03 modules.symbols.bin
lrwxrwxrwx.  1 root root       5 Apr 13 04:37 source -> build
-rw-------.  1 root root 3777432 Apr 13 04:36 System.map
drwxr-xr-x.  2 root root    4096 Apr 13 04:35 updates
drwxr-xr-x.  2 root root    4096 Apr 20 19:55 vdso
-rwxr-xr-x.  1 root root 8212664 Apr 13 04:37 vmlinuz

Could you collect some more information? Try something like this:
[acooks@t460s tn40xx-driver]$ make --recon  -C /lib/modules/4.15.17-300.fc27.x86_64/build M=~/tn40xx-driver

**Comment by hronus** [comment]
pvei7 tn40xx-driver # make --recon -C /lib/modules/4.15.17-1-pve/build M=~/tn40xx-driver
make: Entering directory '/usr/src/linux-headers-4.15.17-1-pve'
mkdir -p /root/tn40xx-driver/.tmp_versions ; rm -f /root/tn40xx-driver/.tmp_versions/*
test -e ./Module.symvers || ( \
echo; \
echo "  WARNING: Symbol version dump ./Module.symvers"; \
echo "           is missing; modules will have no dependencies and modversions."; \
echo )
make -f ./scripts/Makefile.build obj=/root/tn40xx-driver
make[1]: *** No rule to make target '/root/tn40xx-driver/tn40.o', needed by '/root/tn40xx-driver/tn40xx.o'.  Stop.
Makefile:1552: recipe for target '_module_/root/tn40xx-driver' failed
make: *** [_module_/root/tn40xx-driver] Error 2
make: Leaving directory '/usr/src/linux-headers-4.15.17-1-pve'

**Comment by hronus** [comment]
And kernel 4.13 
pvei7 tn40xx-driver # make --recon -C /lib/modules/4.13.13-5-pve/build M=~/tn40xx-driver       
make: Entering directory '/usr/src/linux-headers-4.13.13-5-pve'
mkdir -p /root/tn40xx-driver/.tmp_versions ; rm -f /root/tn40xx-driver/.tmp_versions/*
test -e ./Module.symvers || ( \
echo; \
echo "  WARNING: Symbol version dump ./Module.symvers"; \
echo "           is missing; modules will have no dependencies and modversions."; \
echo )
make -f ./scripts/Makefile.build obj=/root/tn40xx-driver
set -e;  echo '  AR      /root/tn40xx-driver/built-in.o';  rm -f /root/tn40xx-driver/built-in.o; ar rcSTPD /root/tn40xx-driver/built-in.o; printf '%s\n' 'cmd_/root/tn40xx-driver/built-in.o :=  rm -f /root/tn40xx-driver/built-in.o; ar rcSTPD /root/tn40xx-driver/built-in.o' > /root/tn40xx-driver/.built-in.o.cmd
...............................................
{ echo /root/tn40xx-driver/tn40xx.ko; echo /root/tn40xx-driver/tn40.o /root/tn40xx-driver/CX4.o /root/tn40xx-driver/CX4_Linux.o /root/tn40xx-driver/QT2025_phy.o /root/tn40xx-driver/QT2025_phy_Linux.o /root/tn40xx-driver/TLK10232_phy.o /root/tn40xx-driver/TLK10232_phy_Linux.o /root/tn40xx-driver/AQR105_phy.o /root/tn40xx-driver/AQR105_phy_Linux.o; \
   echo; } > /root/tn40xx-driver/.tmp_versions/tn40xx.mod
(cat /dev/null;   echo kernel//root/tn40xx-driver/tn40xx.ko;) > /root/tn40xx-driver/modules.order
:
echo '  Building modules, stage 2.';
make -f ./scripts/Makefile.modpost
echo '  MODPOST 0 modules'; find /root/tn40xx-driver/.tmp_versions -name '*.mod' | xargs -r grep -h '\.ko$' | sort -u | sed 's/\.ko$/.o/' | scripts/mod/modpost -m -a -i ./Module.symvers -I /root/tn40xx-driver/Module.symvers  -o /root/tn40xx-driver/Module.symvers -S  -w  -s -T - 
make: Leaving directory '/usr/src/linux-headers-4.13.13-5-pve'

**Comment by hronus** [comment]
It was a bug of Proxmox with kernel-headers.
