### ISSUE TITLE
missing MV88X3310_phy.h header in last release

### ISSUE THREAD

**Issue by AmaurX** [acooks/tn40xx-driver#24]
As the title says, the header for this driver is missing in release 003. I added back the one from 002 and it seems to work now.

**Comment by acooks** [comment]
MV88X3310_phy.h in release 001 is the firmware for the Marvell PHY extracted from 88X3140-FW-R02-06-03.hdr and is not in release 002 or release 003.

It can not be provided in any future releases until it is made available by Marvell under a distributable license.
