### ISSUE TITLE
Unable to install with Kernel 5.18.0-0.deb11.4

### ISSUE THREAD

**Issue by worksasintended** [acooks/tn40xx-driver#52]
```dkms install  -m tn40xx -v 004

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j40 KERNELRELEASE=5.18.0-0.deb11.4-amd64 -C /lib/modules/5.18.0-0.deb11.4-amd64/build M=/var/lib/dkms/tn40xx/004/build...(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.18.0-0.deb11.4-amd64 (x86_64)
Consult /var/lib/dkms/tn40xx/004/build/make.log for more information.```

[make.log](https://github.com/acooks/tn40xx-driver/files/9530564/make.log)

**Comment by worksasintended** [comment]
https://github.com/worksasintended/tn40xx-driver
this one works. Thanks to @cahz, you did 99.9% of the work. 
[The commit ](https://github.com/worksasintended/tn40xx-driver/commit/b11e0302cf0dbe1d699af0fb1a35a7b38004e767) only had a minor issue forgetting the variable names in the function definition

**Comment by cahz** [comment]
Ah sorry and thanks for pointing it out. I apparently mixed up my patch management (I have a private fork for internal use) and based my public commit on [skwerlman's commit](https://github.com/skwerlman/tn40xx-driver/commit/a9f31bacee8b4304c24f24323fcd27d9cc8d3114), which fixed another issue.

**Comment by devadattas** [comment]
Hi @worksasintended ,

Checking in if this issue got resolved? I am facing a similar issue here https://github.com/acooks/tn40xx-driver/issues/53

**Comment by oktay89** [comment]
I can't install the drivers on my proxmox v7.4.3:
Hardware:
CPU: i5 4690k 
PCI LAN Card: Delock 10gbit RJ45 (recognised as TN9510 10Gbase)
Motherboard: Asus H81I-Plus
```
git clone -b release/tn40xx-004 https://github.com/acooks/tn40xx-driver.git /usr/src/tn40xx-004
dkms add -m tn40xx -v 004
dkms install -m tn40xx -v 004
```

This is the error i get:
```
Error! Bad return status for module build on kernel: 5.15.107-2-pve (x86_64)
Consult /var/lib/dkms/tn40xx/004/build/make.log for more information.
```

I already tried to clone the forks of the original repository like this:
```
git clone -b release/tn40xx-004 https://github.com/skwerlman/tn40xx-driver.git /usr/src/tn40xx-004-skwerlman
dkms add -m tn40xx -v 004-skwerlman
dkms install -m tn40xx -v 004-skwerlman
```

Also tried this repo: https://github.com/worksasintended/tn40xx-driver
Still getting the same error. I think my Proxmox just tries to install the original repo. Is some of my commands wrong?

This is the logfile:
make: Entering directory '/usr/src/linux-headers-5.15.107-2-pve'
  CC [M]  /var/lib/dkms/tn40xx/004/build/tn40.o
  CC [M]  /var/lib/dkms/tn40xx/004/build/CX4.o
  CC [M]  /var/lib/dkms/tn40xx/004/build/CX4_Linux.o
  CC [M]  /var/lib/dkms/tn40xx/004/build/QT2025_phy.o
/var/lib/dkms/tn40xx/004/build/tn40.c:3877:11: warning: ‘struct kernel_ethtool_ringparam’ declared inside parameter list will not be visible outside of this definition or declaration
 3877 |    struct kernel_ethtool_ringparam *kernel_ering,
      |           ^~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/tn40xx/004/build/tn40.c:3898:11: warning: ‘struct kernel_ethtool_ringparam’ declared inside parameter list will not be visible outside of this definition or declaration
 3898 |    struct kernel_ethtool_ringparam *kernel_ering,
      |           ^~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/tn40xx/004/build/tn40.c: In function ‘bdx_ethtool_ops’:
/var/lib/dkms/tn40xx/004/build/tn40.c:4113:20: error: initialization of ‘void (*)(struct net_device *, struct ethtool_ringparam *)’ from incompatible pointer type ‘void (*)(struct net_device *, struct ethtool_ringparam *, struct kernel_ethtool_ringparam *, struct netlink_ext_ack *)’ [-Werror=incompatible-pointer-types]
 4113 |   .get_ringparam = bdx_get_ringparam,
      |                    ^~~~~~~~~~~~~~~~~
/var/lib/dkms/tn40xx/004/build/tn40.c:4113:20: note: (near initialization for ‘bdx_ethtool_ops.get_ringparam’)
/var/lib/dkms/tn40xx/004/build/tn40.c:4114:20: error: initialization of ‘int (*)(struct net_device *, struct ethtool_ringparam *)’ from incompatible pointer type ‘int (*)(struct net_device *, struct ethtool_ringparam *, struct kernel_ethtool_ringparam *, struct netlink_ext_ack *)’ [-Werror=incompatible-pointer-types]
 4114 |   .set_ringparam = bdx_set_ringparam,
      |                    ^~~~~~~~~~~~~~~~~
/var/lib/dkms/tn40xx/004/build/tn40.c:4114:20: note: (near initialization for ‘bdx_ethtool_ops.set_ringparam’)
  CC [M]  /var/lib/dkms/tn40xx/004/build/QT2025_phy_Linux.o
  CC [M]  /var/lib/dkms/tn40xx/004/build/TLK10232_phy.o
  CC [M]  /var/lib/dkms/tn40xx/004/build/TLK10232_phy_Linux.o
  CC [M]  /var/lib/dkms/tn40xx/004/build/AQR105_phy.o
cc1: some warnings being treated as errors
make[1]: *** [scripts/Makefile.build:297: /var/lib/dkms/tn40xx/004/build/tn40.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:1909: /var/lib/dkms/tn40xx/004/build] Error 2
make: Leaving directory '/usr/src/linux-headers-5.15.107-2-pve'

**Comment by acooks** [comment]
fixed in release/tn40xx-006
