### ISSUE TITLE
Getting TN9710P / RC-NIC412v2 Working

### ISSUE THREAD

**Issue by Infinality** [acooks/tn40xx-driver#6]
I'm not posting a problem, rather a solution that can help someone else in the future!  How I got my Rosewill RC-NIC412v2 working, which doesn't work with the default build of this tn40xx driver:

git clone -b release/tn40xx-001 https://github.com/acooks/tn40xx-driver.git /usr/src/tn40xx-001
cd /usr/src/tn40xx-001/
wget https://github.com/acooks/tn40xx-driver/files/2213763/MV88X3310_phy.h.zip
unzip MV88X3310_phy.h.zip 
make MV88X3310=YES
make install
modprobe tn40xx

$ lshw -class network
  *-network                 
       description: Ethernet interface
       product: TN9710P 10GBase-T/NBASE-T Ethernet Adapter
       vendor: Tehuti Networks Ltd.
       physical id: 0
       bus info: pci@0000:02:00.0
       logical name: enp2s0
       version: 00
       serial: 68:1c:a2:13:09:20
       capacity: 10Gbit/s
       width: 64 bits
       clock: 33MHz
       capabilities: msi pm pciexpress bus_master cap_list ethernet physical tp 100bt-fd 1000bt-fd 10000bt-fd autonegotiation
       configuration: autonegotiation=on broadcast=yes driver=tn40xx driverversion=0.3.6.17 duplex=full firmware=N/A ip=192.168.0.244 latency=0 link=yes multicast=yes port=twisted pair

EDIT:  I used the upstream source for this particular build.  
         wget http://www.tehutinetworks.net/images/UL240756/tn40xx-0.3.6.17.tgz

**Comment by sajor2006** [comment]
[   96.647031] tn40xx: loading out-of-tree module taints kernel.
[   96.647120] tn40xx: module verification failed: signature and/or required key missing - tainting kernel
[   96.647957] Tehuti Network Driver from https://github.com/acooks/tn40xx-driver, 004
[   96.647959] Supported phys :    QT2025 TLK10232 AQR105 MUSTANG
