### ISSUE TITLE
tn40xx: rxd_err = 0x10

### ISSUE THREAD

**Issue by ThibautBascoulergue** [acooks/tn40xx-driver#7]
Hi,

I have an LR-Link card in SFP + installed in an esxi 6.5.
And in the logs I have only WARNING: tn40xx: rxd_err = 0x10

Is it possible to build this driver under Esx?

Thank you

**Comment by acooks** [comment]
I don't know anything about Esx, sorry. But since you're talking about commercial software and not Linux, perhaps you could get support from your vendor. Good luck!
